### ISSUE TITLE
Runing in container

### ISSUE THREAD

**Issue by haos616** [flant/pam_docker#3]
Is it possible to run it in a container?

**Comment by dmgtn** [comment]
Hypothetically — yes, but it should be, at least, privileged container. And no one tried this, of course.

**Comment by haos616** [comment]
@distol It works!
Need use `--pid='host'  --privileged -v '/var/run/docker.sock:/var/run/docker.sock'`

**Comment by dmgtn** [comment]
Cool! @distorhead gave me the hint that we already run tests same way: https://github.com/flant/pam_docker/blob/master/Buildizer#L77.
